Repository apple/swift-openapi-generator, pull requests merged in 2023-07, with the labels that each got.

#110 Move DocC and integration tests into separate CI pipelines
  docker/docker-compose.yaml
  scripts/soundness.sh
Labels: semver/none

#108 Simplify swift-format soundness script
  Package.swift
  scripts/run-swift-format.sh
Labels: semver/none

#109 Generate @frozen enums for operation outputs and request/response bodies
  Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
  Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
  Sources/_OpenAPIGeneratorCore/Translator/TypesTranslator/translateOperations.swift
  Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Types.swift
Labels: semver/minor

#121 [Tests] Add an integration test product for easier iteration
  IntegrationTest/Package.swift
Labels: semver/none

#137 fix: Correct data type of date-formatted strings
  Sources/_OpenAPIGeneratorCore/Translator/TypeAssignment/TypeMatcher.swift
  Sources/swift-openapi-generator/Documentation.docc/Development/Converting-between-data-and-Swift-types.md
  Tests/OpenAPIGeneratorCoreTests/Translator/TypeAssignment/Test_TypeMatcher.swift
Labels: semver/patch

#156 Fix server handler Sendability warnings
  Sources/_OpenAPIGeneratorCore/Translator/ServerTranslator/translateServerMethod.swift
  Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Server.swift
Labels: semver/patch

#155 Fix various typos in docc articles
  Sources/swift-openapi-generator/Documentation.docc/Articles/API-stability-of-generated-code.md
  Sources/swift-openapi-generator/Documentation.docc/Articles/Contributing-to-Swift-OpenAPI-Generator.md
  Sources/swift-openapi-generator/Documentation.docc/Articles/Project-scope-and-goals.md
Labels: semver/none

#152 [Generator] Design away EncodableBodyContent
  Package.swift
  Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
  Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift
  Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Client.swift
  Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Server.swift
Labels: semver/none
