Repository apple/swift-openapi-generator, pull requests merged in 2023-06, with the labels that each got.

#53 [Releases] Add a release config
  .github/release.yml
Labels: semver/none

#58 docs: Emphasize target setting in Xcode tutorial
  Sources/swift-openapi-generator/Documentation.docc/Tutorials/ClientXcode.tutorial
Labels: semver/none

#60 [Docs] Add a link to the WWDC talk
  README.md
  Sources/swift-openapi-generator/Documentation.docc/Swift-OpenAPI-Generator.md
Labels: area/documentation, kind/enhacement, semver/none

#68 [Docs] Update the generator minimum version
  README.md
  Sources/swift-openapi-generator/Documentation.docc/Swift-OpenAPI-Generator.md
Labels: semver/none

#80 docs: Update instructions for running developer scripts
  CONTRIBUTORS.txt
  scripts/generate-contributors-list.sh
Labels: semver/none

#85 Specify default code listing language for DocC catalog
  Sources/swift-openapi-generator/Documentation.docc/Articles/Configuring-the-generator.md
  Sources/swift-openapi-generator/Documentation.docc/Info.plist
Labels: semver/none

#81 Emit YAML processing errors that Xcode can display
  Sources/_OpenAPIGeneratorCore/Diagnostics.swift
  Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
  Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
  Tests/OpenAPIGeneratorCoreTests/Parser/Test_YamsParser.swift
Labels: semver/patch

#88 Add `await` and `Protocol` to the identifiers escaping rules
  Sources/_OpenAPIGeneratorCore/Extensions/String.swift
Labels: semver/patch

#87 Emit a descriptive error when running the generator on iOS, tvOS, or watchOS
  Package.swift
  Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
Labels: semver/patch

#91 docs: Update proposal process
  Sources/swift-openapi-generator/Documentation.docc/Proposals/Proposals.md
Labels: area/documentation, semver/none
