Repository apple/swift-openapi-generator, pull requests merged in 2024-11, with the labels that each got.

#670 unify scheduled and main yamls
  .github/workflows/main.yml
  .github/workflows/scheduled.yml
Labels: semver/none

#672 remove unused Swift 6 language mode workflow
  .github/workflows/pull_request.yml
Labels: semver/none

#626 [Proposal] SOAR-0011: Improved error handling
  Sources/swift-openapi-generator/Documentation.docc/Proposals/Proposals.md
  Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
Labels: kind/proposal

#671 add .editorconfig file
  .editorconfig
  .licenseignore
Labels: semver/none

#684 Add GitHub action to check for Semantic Version label
  .github/workflows/pull_request_label.yml
Labels: semver/none

#646 [Generator] Improve parameter handling of MIME types in content types
  Sources/_OpenAPIGeneratorCore/Translator/Content/ContentType.swift
  Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
Labels: semver/patch
