Repository apple/swift-openapi-generator, pull requests merged in 2025-01, with the labels that each got.

#708 Add a CLI option for selecting the naming strategy
  Sources/_OpenAPIGeneratorCore/Config.swift
  Sources/_OpenAPIGeneratorCore/Layers/StructuredSwiftRepresentation.swift
  Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
  Sources/swift-openapi-generator/GenerateOptions.swift
Labels: 🆕 semver/minor

#709 Add missing imports to fix Swift 6.1+
  .github/workflows/pull_request.yml
  Sources/_OpenAPIGeneratorCore/Extensions/SwiftStandardLibrary.swift
  Sources/_OpenAPIGeneratorCore/Translator/CommonTypes/StructBlueprint.swift
  Sources/_OpenAPIGeneratorCore/Translator/Content/ContentInspector.swift
  Sources/_OpenAPIGeneratorCore/Translator/TypesTranslator/translateServersVariables.swift
Labels: 🔨 semver/patch

#713 [Cleanup] Make Config's namingStrategy and accessModifier params consistent
  Sources/_OpenAPIGeneratorCore/Config.swift
  Tests/OpenAPIGeneratorCoreTests/Parser/Test_YamsParser.swift
  Tests/OpenAPIGeneratorCoreTests/Parser/Test_validateDoc.swift
  Tests/OpenAPIGeneratorCoreTests/Translator/TypeAssignment/Test_isSchemaSupported.swift
  Tests/OpenAPIGeneratorReferenceTests/CompatabilityTest.swift
  Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
Labels: 🔨 semver/patch

#722 CI use 6.1 nightlies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
